### ISSUE TITLE
Geopoint in polygon

### ISSUE THREAD

**Issue by synw** [wingkwong/geodesy#1]
Hi. I have seen there is a `isGeoPointInBoudingBox` function. I'm looking for a way to tell if a geopoint is in a given polygon. 

Would a `isGeoPointInPolygon` function be doable?

**Comment by wingkwong** [comment]
@synw Sorry for the late reply. Yes. It is doable and will be released in the next batch soon.

**Comment by wingkwong** [comment]
@synw `isGeoPointInPolygon` was introduced in 0.2.0. For usage, please check out `main.dart` in example folder.
