### ISSUE TITLE
Polygons intersection

### ISSUE THREAD

**Issue by adnanefouam** [wingkwong/geodesy#15]
Any idea howa to get the intesection between the blue polygon and the grey one ? Thanks

![CCA41664-2EC3-465E-95BB-982826A304D0](https://user-images.githubusercontent.com/59290932/95670350-cba1d700-0b81-11eb-8bf7-e177fd3cdae5.jpeg)

**Comment by barbalex** [comment]
You could be inspired by:
https://github.com/Turfjs/turf/blob/master/packages/turf-intersect/index.ts#L58-L65
which uses: https://github.com/mfogel/polygon-clipping

Unfortunately that is JavaScript.

**Comment by wingkwong** [comment]
Available in `0.6.0`
