### ISSUE TITLE
Use the LatLong package?

### ISSUE THREAD

**Issue by synw** [wingkwong/geodesy#4]
Hi, would it be possible to use the LatLong(https://pub.dartlang.org/packages/latlong) package for standard coordinates data structure? It looks pretty solid (it enforces 90/-90 degrees constrains for latitude and longitude for example) and standard (it is used in great packages like [Flutter map](https://github.com/johnpryan/flutter_map)).

It could reduce duplicated maintenance work. Your module covers a much more broader scope it could makes sense to use it. And also to provide a standard data format across packages: example: I have a list of these coordinates and want to pass it to `isGeoPointInPolygon`: for now I have to convert it to use your class, which has an unpleasant cost.

**Comment by wingkwong** [comment]
@synw Thanks for recommending it. Just took a look at it. It would probably use it in the next batch.

**Comment by wingkwong** [comment]
@synw please use the latest version, i.e. 0.3.0
