### ISSUE TITLE
error in calculatePolygonArea unit

### ISSUE THREAD

**Issue by Nico04** [wingkwong/geodesy#42]
In my cartographic app I have a tool to measure a distance and a surface with user selected points.
I've used [Geoportail](https://www.geoportail.gouv.fr/carte) to check if measurment is correct (just measuring the same thing in my app and the website).
While distance using `distanceBetweenTwoGeoPoints` seems correct, area using `calculatePolygonArea` looks quite wrong.
When Geoportail says 0.116km², `distanceBetweenTwoGeoPoints` returns `0.00001370770505371155` m², which is not at all the same.
After a quick look [at the code](https://github.com/wingkwong/geodesy/blob/master/lib/src/core/GeodesicMeasurements/polygon_area_by_points.dart), maybe there is a unit mismatch ? You are summing & multiplying lat & lng values directly, which are not meters, and returning directly that value in supposely m².
Something looks wrong ?

EDIT : when looking at some other algo, they look very different, using more advanced math trigonometry ?
https://github.com/dartclub/turf_dart/blob/bbccfb3cebb532a2e8341294f30590ae8a541b5d/lib/src/area.dart#L74
https://github.com/divvitco/geodart/blob/be4016f1b74baf5dcf54fef7ce5e3ed00028ba0b/lib/src/featureTypes/geometries/linear_ring.dart#L43
https://github.com/kb0/maps_toolkit/blob/540da77cf12d2a1dfceb12183776fb4969020750/lib/src/spherical_util.dart#L186

EDIT: I've compared using `computeArea` of [maps_toolkit](https://pub.dev/packages/maps_toolkit), it work as expected.

**Comment by ayoubzulfiqar** [comment]
## First issue

I have looked into the Problem you are facing and i basically When Your Geoportial is  0.116km² it's in Square KiloMeters but the method returning in meters.

If you can Provide the lat and lng Coordinates That you are using to get `0.116km²` in Geoportail It would be easy for to debug
So Please provide the refrence data


```dart
extension Unit on num{
// assuming a square area
 double get metersToSquareKilometers => this * this / 1e6;
}
```

Example

```dart
  final Geodesy geo = Geodesy();
  final l1 = const LatLng(-5.06638889, -5.71472222);
  final l2 = const LatLng(-8.64388889, -3.07000000);
  final dis = geo.distanceBetweenTwoGeoPoints(l1, l2);
  print("Distance Meters: $dis");
  print("Distance Meter to Square: ${dis.metersToSquareKilometers}");
```

and you can use this extension to convert this value `0.00001370770505371155 m²` to this `0.116km²` with less precision


## Second Issue

When looking at the  CalculatePolygonArea Method. It has little mistake. Thanks for Pointing out.
Now I have used Shoelace formula to calculate the for finding the area of a polygon given the coordinates of its vertices.

The formula you've used in your code is a variation of the Shoelace formula, which is a method for finding the area of a polygon given the coordinates of its vertices. However, there seems to be a mistake in your code. The correct formula is:


 Also Updated in the main code Soon all the Changes will be reflected into the main code and other unit conversion methods
```dart
double calculatePolygonArea(List<LatLng> polygonPoints) {
  if (polygonPoints.length < 3) {
    // A polygon must have at least 3 points to form an area.
    return 0.0;
  }

  double area = 0.0;

  for (int i = 0; i < polygonPoints.length; i++) {
    final LatLng currentPoint = polygonPoints[i];
    final LatLng nextPoint = polygonPoints[(i + 1) % polygonPoints.length];

    area += (currentPoint.latitude * nextPoint.longitude - nextPoint.latitude * currentPoint.longitude);
  }

  area = area.abs() / 2.0;
  return area;
}
```

I've corrected the formula inside the loop to match the Shoelace formula. Now, the code should correctly calculate the area of a polygon given its vertices.
