### ISSUE TITLE
Geofence geopoints located in a distance radius from a given geopoint

### ISSUE THREAD

**Issue by synw** [wingkwong/geodesy#7]
Hi. I am looking for a way to get a circular line around a geopoint calculated from a distance. Would it be doable?

[Edit]: more precisely what is needed is to find the geopoints located in a radius from a given geopoint, passing a list of geopoints to check

**Comment by wingkwong** [comment]
@synw could you provide an example with input and output?

**Comment by synw** [comment]
Maybe something like that:

```dart
final point = LatLng(0,0);
final distanceInMeters = 10000;
final pointsToSearchIn = <LatLng>[
  // points here
];
List<LatLng> pointsInRadius = pointsInDistanceRadius(
  point: point,
  searchPoints: pointsToSearchIn,
  distance: distanceInMeters,
)
```
It would be great to also be able get a circle from the point and the distance:

```dart
final point = LatLng(0,0);
final distanceInMeters = 10000;
List<LatLng> circle = circleFromDistanceRadius(
  point: point,
  distance: distanceInMeters
)
```

Use case: print some markers on a map within a certain distance from the current location. It would be fine to be able to print a circular line to see the distance radius on the map

**Comment by synw** [comment]
I managed to handle this by just checking the distance from center for every point:

```dart
List<LatLng> pointsWithinDistance(
      {@required LatLng point,
      @required List<LatLng> pointsToCheck,
      @required num distance}) {
    final geoFencedPoints = <LatLng>[];
    for (final p in pointsToCheck) {
      final distanceFromCenter = distanceBetweenTwoGeoPoints(point, p);
      if (distanceFromCenter <= distance) {
        geoFencedPoints.add(p);
      }
    }
    return geoFencedPoints;
  }
```
Do you want a pr to include this in the lib or is it not worth it? It may help dumb people like me that do not think about it in the first place

**Comment by wingkwong** [comment]
@synw PR is welcome. Before that, please add the test case.

**Comment by synw** [comment]
Are you okay with the named parameters or do you want to keep using only positional ones? Note: the `@required` is from the `meta` package. Being used to Flutter where all is named I think the named parameters are more easy to use from my experience

**Comment by wingkwong** [comment]
@synw if these three fields are required, why don't you just use required parameters instead of using optional named parameters with required meta tags?

**Comment by synw** [comment]
The code is easier to read when using named parameters. I'll switch to positional parameters here to match this library's style

**Comment by wingkwong** [comment]
@synw please help update README.md for what you made. Thanks.

**Comment by synw** [comment]
@wingkwong #13 : documented. On the way I formatted the readme to valid markdown, colorized the Dart code and added a pub badge
